services:
  backend:
    restart: always
    container_name: mediaserver-backend
    volumes:
      - static:/app/static
    env_file:
      - backend/backend/.env
    build:
      context: ./backend
    ports:
      - "8081:8081"
    


  nginx:
    restart: always
    container_name: mediaserver-nginx
    build:
      context: ./nginx
    volumes:
      - static:/app/static
    ports:
      - "8080:8080"
    depends_on:
      - backend

 

volumes:
  static: